services:
  - type: web
    name: project-management-system
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    plan: free
    envVars:
      - key: SECRET_KEY
        value: 08d8440116c5b8b558bd90d064310f2aeb9846ae028c3c89b66d4e289baa5fbe
      - key: DATABASE_TYPE
        value: postgresql
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
